name: "Build and deploy 5432"

on:
  push:         
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: "Install Python dependencies"
        run: |
          python -m pip install -r requirements.txt

      - name: "Build Sphinx Doc"
        run: |
          make html

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages     
          FOLDER: build/html/  

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/html/
          server-dir: www/
