name: "Build and deploy 5432"

on:
  push:         
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm build

      - name: Setup IndexNow
        run: echo ${{ secrets.INDEXNOW_KEY }} > ./dist/${{ secrets.INDEXNOW_KEY }}.txt  

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          log-level: "minimal"
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: www/

      - name: IndexNow
        uses: bojieyang/indexnow-action@v2 # v2 is the latest major version following the action-versioning.
        with:
          sitemap-location: "https://5432.fr/sitemap.xml"
          since: 2
          since-unit: "day"
          key: ${{ secrets.INDEXNOW_KEY }} # The key you get from IndexNow.          
